### ISSUE TITLE
How to control the scale between prediction and groud truth label in your model?

### ISSUE THREAD

**Issue by ddshan** [hassony2/obman_train#1]
In your obman dataset, the groud truth for coords_3d and verts_3d are in range probably [-1, 1], while the 3D construction of the hands are in a larger range ( probably [-120, 120]. according to the right part of the mug.png ).

**Ground Truth:**
![2](https://user-images.githubusercontent.com/43507322/59959496-512ddf00-9486-11e9-8bb4-006494cc4525.png)
**Prediction:**
![1](https://user-images.githubusercontent.com/43507322/59959499-5e4ace00-9486-11e9-8af8-7bfcbd6d4338.png)

My question is how to control the scale between the 3D prediction and the groud truth in you rmodel, so that they are comparable when calculating the loss.

Thanks.

PS:
I have used GANerated Hand Dataset before, and its 3D joints GT is normalized (similar as yours, but there is no document for your dataset, hope to see your details for labels). In that case, I multiply the normalized 3D joints GTs by 95 to make it comparable with the predictions ( After experiments, I found the stable scale between the normalize GT and3d joints of mano prediction, which is nearly 95. So, I chose 95 ). 

However, after reading your code entirely for several times, I have still not found any scalar (like 95) or sth like that in your code. So, I suspect that I neglect some important detail. Hope to hear from your response soon!

**Comment by hassony2** [comment]
Hi !

In the [obman](https://github.com/hassony2/obman) repository, dimensions are in meters, in obman_train I work with millimeters. 
You can find the multiplication by 1000 here : https://github.com/hassony2/obman_train/blob/5522274bf1b972f52ac5418e0f1069da0d8b3012/handobjectdatasets/obman.py#L351.

Best,

Yana
