### ISSUE TITLE
Following Error

### ISSUE THREAD

**Issue by nitba** [hassony2/obman_train#10]
Hi @gulvarol 

Whaat should I do to avoid this error.

,`s/manobranch.py", line 300, in compute_loss
    preds["shape"], torch.zeros_like(preds["shape"])
TypeError: zeros_like() received an invalid combination of arguments - got (NoneType), but expected one of:
  (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
`

**Comment by hassony2** [comment]
Hi !

You should add --mano_use_shape so that the shape is also predicted :)

**Comment by Ivamcoder** [comment]
Hi @hassony2 ,

Thank you so much for your comment, I could run but for validation I got this results,  which has  `2mm` error more than the reported table,  how I could reach to `10mm` mean epe?

`(epoch: 30, time: Tue Oct  8 10:15:08 2019),mano_total_loss:77.73668052803757,mano_joints3d:72.90256040524214,epe_median:10.992660522460938,mano_shape:4.353974868089725,auc:0.7554753436743569,epe_mean:12.291057586669922,total_loss:77.73668052803757,pose_reg:2.875123557371971
`
