### ISSUE TITLE
How to train the model on First-Person Hand Action Benchmark?

### ISSUE THREAD

**Issue by TerenceCYJ** [hassony2/obman_train#11]
Hi @hassony2 ,
Thanks for your great work!
I would like to train the model on First-Person Hand Action Benchmark. Could you please share how do you implement it? 
Sincerely thank you very much! #

**Comment by hassony2** [comment]
Hi !

Sorry for the late response.
You can find the final parameters to train on the FPHAB dataset in the file : 
release_models/fhb/opt.txt

The model should be first trained without the contact loss (otherwise the training is very slow) and then finetuned with contact :)

**Comment by TerenceCYJ** [comment]
@hassony2  Thank you for the reply.
But the two dataset is different, and the data processing should be different. For example, image on obman is [256, 256], and on FHAB is [1920,1080]. When do the rotate, tranlate, and crop, there should be some different. But when I use the code, the cropped image on FHAB is apperantly wrong. Could you please tell me how do you do that on FHAB dataset? 
Thank you very much!

![Base_color](https://user-images.githubusercontent.com/25705382/68428223-be15ed00-0179-11ea-8e9a-b686af51ec0e.jpg)
![Trans_color](https://user-images.githubusercontent.com/25705382/68428236-c2420a80-0179-11ea-9cac-90cc98542fd9.jpg)

**Comment by TerenceCYJ** [comment]
This can be solved if the 2D joints are correct. 
Thanks! @hassony2

**Comment by JudyYe** [comment]
Just a further comment that to get 2D joints correct, all you need is to downsample the images by a factor of 4. Yana kindly wrote it in the code. Thank you for the detailed comment! Save us lots of time.
