### ISSUE TITLE
About Hand mesh regression.

### ISSUE THREAD

**Issue by www516717402** [hassony2/obman_train#19]
Thank you for great project.
I read your paper recently. Why not supervised theta In **Sec3.1** since the more supervised, the higher accuracy in appendix A1. And regress theta Easier than vetex because smaller space. So, I gauss expend theta will obtain a good result or not too bad.

**Comment by hassony2** [comment]
Hi !

We did not experiment with supervising theta in this case, which could be or not beneficial, I would have to try ! :)
Although the vertex prediction is done in a larger space, the network still outputs the low-dimensional PCA parameters, and then the higher dimensional vertices are obtained in a deterministic way. Therefore, it is unclear to me whether supervising the theta parameters should perform better :)

Best,

Yana
