### ISSUE TITLE
black margin after calling tranform_img()

### ISSUE THREAD

**Issue by ddshan** [hassony2/obman_train#2]
<img width="162" alt="transform" src="https://user-images.githubusercontent.com/43507322/59950207-37b77380-9443-11e9-80c1-b7373dbe8667.png">

Do you have the problem of black margin after calling the `handutils.tranform_img()` function?
Do you have any idea to solve it?

**Comment by ddshan** [comment]
I tried to use the following functions to remove the black margin and then resize it to (256, 256).

`from PIL import Image`
`image = image.crop(image.getbbox())`
` image = image.resize((256, 256))`

But, another problem occurs. This leads to mismatch between joints2d coordinates and the cropped image.

<img width="107" alt="resize" src="https://user-images.githubusercontent.com/43507322/59955073-1a3fd500-9456-11e9-86d0-2eb77dc4b3f5.png">


So, I assume that just keep the black part during training, right?
But, it is kind of weird. What do you think about this? Does it help to prevent overfitting?

**Comment by hassony2** [comment]
Hi @ddshan,

The black margin is the intended behaviour, the model learns to not take it into account.
You could adapt the code to change the margin behaviour if you wish to.
