### ISSUE TITLE
questions about Camera Intrinsics  when applied [post_rot_trans] 

### ISSUE THREAD

**Issue by lixiny** [hassony2/obman_train#20]
Hi Hasson, Thanks for your great work.
in codes [handataset.py](https://github.com/hassony2/obman_train/blob/master/handobjectdatasets/handataset.py), line #202, 
I found that when applying the perspective camera projection to the **(new)_joint3d** by the **new_camintr**, the results is not equal to  the ground truth **(new)_joints2d**(in your codes: "rows" at line #193).
Could you please explain the inconsistency when you applied the data augmentation (max_rot = 0.5 PI ) ? 

Best

**Comment by lixiny** [comment]
we solved the issue by modifying [handutils.py](https://github.com/hassony2/obman_train/blob/master/handobjectdatasets/handutils.py), line 77-78:
original:
```
    t_mat[0, 2] = -res[1] / 2
    t_mat[1, 2] = -res[0] / 2
```

to 
```
    t_mat[0, 2] = - {optical center at x, or Cx in your original camera intrinsic}
    t_mat[1, 2] = - {optical center at y, or Cy in your original camera intrinsic}
``` 

This bug won't happen in OBMAN dataset, since the `intr` in OBMAN is synthetic and perfectly equals to half of the image size (128) , But I found that when using the same data augmentation codes to other datasets (eg: STB / RHD / FreiHand), there will be a problem.

Hope you see my comments.

**Comment by hassony2** [comment]
@lixiny thank you very much for this !
Indeed, this code is mostly tested with FHB and Obman, so for other datasets inconsistent behaviour can occur.

I will keep this in mind in case other people come across similar issues.
