### ISSUE TITLE
torch 1.6.0 raise error in contactutils.py 150: not_parallel = 1 - parallel 

### ISSUE THREAD

**Issue by Hobeom** [hassony2/obman_train#23]
https://github.com/hassony2/obman_train/blob/83be15c342e24b332555b75b69544cb2eaa65cdb/mano_train/networks/branches/contactutils.py#L150

change to
```
not_parallel = parallel.logical_not()
```

**Comment by hassony2** [comment]
Thank you very much @HoBeom for flagging this issue !

Fixed here [cc9dd72e94511a7c896034f7705e84f72afcc073](https://github.com/hassony2/obman_train/commit/cc9dd72e94511a7c896034f7705e84f72afcc073)

Have a great day !

Yana
