### ISSUE TITLE
Relation between 3D joint locations and camera space.

### ISSUE THREAD

**Issue by erezposner** [hassony2/obman_train#5]
Hi, I would like to understand the relation between the MANO 3d joint and vertices 3d location with the camera space.

Let's assume that I capture an RGB image using a calibrated camera and use "Learning joint reconstruction of hands and manipulated objects" to estimate MANO 3d joints. Are the 3d joints are in normalized camera space? 

Would the MANO estimation is oriented towards camera?
Thank you

**Comment by hassony2** [comment]
Hi @erezposner 

MANO 3d joint and vertices are predicted aligned with the camera view, but root centered.
This means that:
- if you keep the two first coordinates of the predicted 3d joints, if you assume an orthographic camera model, there is an additional scaling and translation missing to go back to the image space, so **yes** the Mano estimation is oriented towards the camera
- After the paper was submitted, I did some additional experiments to also predict this scale and translation but for **hands only** (no objects) if you run `python webcam_demo.py --resume release_models/hands_only/checkpoint.pth.tar` you will see that the predicted joints are reprojected onto the image.

I hope this answers your question !

Best,

Yana

**Comment by erezposner** [comment]
Are the scaling and translation estimated within the net? or using closed form solution?
could you kindly direct me this part in the code?
thank you

**Comment by hassony2** [comment]
Sure !

Here are some pointers:
- [initialization of the scale/trans prediction branch](https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/handnet.py#L123)
- [prediction of trans and scale in forward pass](https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/handnet.py#L291)
- [scale trans and joints3d are combined to give joints2d](https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/handnet.py#L299)

**Comment by erezposner** [comment]
Thanks! got it.
I have another question, more in the context of MANO layer.
How can one generate multiple perspectives of the same MANO generated hand? In the sense of beta,thetas.

If I understand correctly, for the same hand viewed from two different perspectives I would have two different theta vectors, Is that correct? If this is the case, How can I determine the theta vector of a hand viewed from another perspective?
thank you

**Comment by hassony2** [comment]
This is correct, the first 3 parameters of theta are the global axis-angle rotation vector, so this is the part that needs to be modified to generate the vector from a different perspective.

**Comment by erezposner** [comment]
Got it, Thank you
