### ISSUE TITLE
GT mesh, vertices

### ISSUE THREAD

**Issue by nitba** [hassony2/obman_train#7]
Hi @hassony2 ,

Thanks for sharing your code, I was wondering for the dataset `Stereohand` or others that we do not have ground truth annotation for beta and theta (pose shape Manao params), we have just 3D joints location,  how you get GTs for supervision ?

**Comment by gulvarol** [comment]
Hi @Ivamcoder ,

Thanks for your interest. As you can see in the appendix (Table A.1 and the Section A.1. 'Loss study on MANO'), the datasets that only have 3D joints supervision are trained only with L_J, the loss on the joint locations.

**Comment by nitba** [comment]
Hi @gulvarol,

Thanks for your reply, we have another supervision which is `L_V_Hand` , and we have GT for `obman` in `meta_info["verts_3d"]`, but for `stereo` we do not have such this information, I was wondering how this supervision is provided for training on `stereohands` .

**Comment by hassony2** [comment]
In MANO, hand joints are regressed from vertices and provided as output of the mano layer (see [this line](https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/branches/manobranch.py#L170)).
Both of these outputs are obtained as a differentiable function of the MANO pose and shape vectors.
You can therefore apply supervision on joints only (see [this line](https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/branches/manobranch.py#L293)), if this is the only supervision available, or on both vertices and joints, as we do when we train on ObMan.
