### ISSUE TITLE
dispalymano

### ISSUE THREAD

**Issue by TerenceCYJ** [hassony2/obman_train#8]
displaymano.py
The `visualoze_contacts3d(),` the dimension of `close_vert` is 1, so we can not get `close_vert[1]` or `close_vert[2]`.

Get `IndexError: invalid index to scalar variable.`

**Comment by hassony2** [comment]
Thank you for reporting this error !
Could you specify which version of PyTorch you are using and which command you are running ?

**Comment by TerenceCYJ** [comment]
Pytorch: 1.1.0
I use the `displaymano.py` for contact visualization and it occured this issue.
Thank you!
